# Generated by Django 2.1.5 on 2019-01-18 07:48

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190118_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='0', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
